### ISSUE TITLE
Not working with Subrion 4.1.3+

### ISSUE THREAD

**Issue by smartey** [intelliants/subrion-plugin-rss_reader#4]
I updated the RRS Reader plugin for Subrion 4.1.3+, I run it on my own website and from what I can see it's working 100% again with latest Subrion version. See Pull request for details.

Regards,
Eric

**Comment by vbezruchkin** [comment]
Thanks for your fixes & improvements Eric. Now works fine.

Please use 4.1.0 version.

**Comment by smartey** [comment]
You're welcome V. I might start working on other plugin not working with latest version, any suggestion?
I wouldn't want to invest time if someone already is working on same plugin fix :)

**Comment by vbezruchkin** [comment]
You're free to make any changes to any plugin. Any comments or improvements would be great. You can check for the plugins that are not compatible yet. At the moment the guys are more focused on packages & core system. And we use git overall so the changes won't be lost :)
